name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag todoapp:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy image
        run: docker run -it -d -p 5000:5000 todoapp:latest
  status:
    runs-on: ubuntu-latest
    steps:
      - name: check status
        run: docker ps -a
        
