name: Docker Image CI

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag todoapp:$(date +%s)
